qsub ./name/sub00 >>./name/jobID.txt
qsub ./name/sub01 >>./name/jobID.txt
qsub ./name/sub02 >>./name/jobID.txt
qsub ./name/sub03 >>./name/jobID.txt
qsub ./name/sub04 >>./name/jobID.txt
qsub ./name/sub05 >>./name/jobID.txt
qsub ./name/sub06 >>./name/jobID.txt
qsub ./name/sub07 >>./name/jobID.txt
qsub ./name/sub08 >>./name/jobID.txt
qsub ./name/sub09 >>./name/jobID.txt
qsub ./name/sub10 >>./name/jobID.txt
qsub ./name/sub11 >>./name/jobID.txt
qsub ./name/sub12 >>./name/jobID.txt
qsub ./name/sub13 >>./name/jobID.txt
qsub ./name/sub14 >>./name/jobID.txt
qsub ./name/sub15 >>./name/jobID.txt
qsub ./name/sub16 >>./name/jobID.txt
qsub ./name/sub17 >>./name/jobID.txt
qsub ./name/sub18 >>./name/jobID.txt
qsub ./name/sub19 >>./name/jobID.txt
qsub ./name/sub20 >>./name/jobID.txt
qsub ./name/sub21 >>./name/jobID.txt
qsub ./name/sub22 >>./name/jobID.txt
qsub ./name/sub23 >>./name/jobID.txt
qsub ./name/sub24 >>./name/jobID.txt
qsub ./name/sub25 >>./name/jobID.txt
qsub ./name/sub26 >>./name/jobID.txt
qsub ./name/sub27 >>./name/jobID.txt
qsub ./name/sub28 >>./name/jobID.txt
qsub ./name/sub29 >>./name/jobID.txt
qsub ./name/sub30 >>./name/jobID.txt
qsub ./name/sub31 >>./name/jobID.txt
qsub ./name/sub32 >>./name/jobID.txt
qsub ./name/sub33 >>./name/jobID.txt
qsub ./name/sub34 >>./name/jobID.txt
qsub ./name/sub35 >>./name/jobID.txt
qsub ./name/sub36 >>./name/jobID.txt
qsub ./name/sub37 >>./name/jobID.txt
qsub ./name/sub38 >>./name/jobID.txt
qsub ./name/sub39 >>./name/jobID.txt
